### ISSUE TITLE
Closing info window closes all windows

### ISSUE THREAD

**Issue by barbeau** [Egan109/core#2]
**Summary:** 

If I click on the "info" buttons to find out more about the field, and then click on the "X" in the upper right corner of the info window to close it, it closes all open windows and exits the application.

**Steps to reproduce:** 
1. Run QuickStart JAR (`transitimeQuickStart.jar`)
2. On the main screen, tap on info button next to any field
3. Tap on close "X" button in upper right corner of info window

**Expected behavior:** 

Close the info window, and leave the main screen open

**Observed behavior:** 

Both info window and main screen are closed.

cc @scrudden

**Comment by Egan109** [comment]
This issue should now be fixed, just needed to change the default close operation of the information Panel. 

-Brendan

**Comment by barbeau** [comment]
@Egan109 Great, thanks!  I'll try it out.  FYI, you can paste a link to the commit here in the issue (or just the commit-id/SHA1) to link them on Github.  Normally you can also reference the issue number in the commit message directly, like:

`Fix #2 - Change default close operation of information panel`

...but because you're working on a fork of the transiTime repo, it may end up referencing/closing issues in that repo instead of your fork.  So the copy/paste solution is probably best when dealing with a fork.

**Comment by Egan109** [comment]
@barbeau Thanks! This is all new to me so I appreciate the advice

here is the commit link-
ea7d7356afc7f0843ce4ee15294d857cf3d9aefa -change the default close operation of the information Panel
