### ISSUE TITLE
Quickstart fails with GTFS and GTFS-realtime feed

### ISSUE THREAD

**Issue by barbeau** [Egan109/core#3]
**Summary:** 

If I try to run the QuickStart with PSTA's GTFS and GTFS-realtime VehiclePositions feed, I get an error message:

> Error in starting TransitimeQuickStart:
> extractResources failed
> null

![image](https://cloud.githubusercontent.com/assets/928045/17602820/4ec22686-5fdc-11e6-92ac-6680c625dc12.png)

GTFS data - [GTFSExport.zip](https://github.com/Egan109/core/files/414092/GTFSExport.zip)

GTFS-realtime vehiclePositions feed - http://ridepsta.net/gtfsrt/vehicles

**Steps to reproduce:** 
1. Run QuickStart JAR (`transitimeQuickStart.jar`)
2. Add links to the above GTFS/GTFS-realtime data
3. Set local directory (I used `F:\temp\transitime`)
   1  Highlight "Start webapp" and click on "Next"

![image](https://cloud.githubusercontent.com/assets/928045/17602827/582ea71c-5fdc-11e6-891e-cd6a85459c5a.png)

**Expected behavior:** 

Go to the next QuickStart screen

**Observed behavior:** 

> Error in starting TransitimeQuickStart:
> extractResources failed
> null

cc @scrudden

**Comment by barbeau** [comment]
I also created "F:\temp\transitime" before clicking "Next".

I'm running on Windows 7 Enterprise 64 bit.

**Comment by barbeau** [comment]
I ran `mvn install -DskipTests` to build the project from the root folder, then went to `\transitimeQuickStart\target` to get the JAR file.

**Comment by scrudden** [comment]
Have asked that the null in the error window be fixed so it shows stacktrace.

**Comment by Egan109** [comment]
@barbeau ExceptionPanel should now display the stacktrace if you want to rerun it so we can see what the issue is.
c16a8a872865096087fa603fccf70c1749d2642b -Exception Panel now displays stacktrace
36985507749ba23b901e7c32a31fae149201ecb4 -fixed a typo created from adding stacktrace to ExceptionPanel

Thanks.

**Comment by barbeau** [comment]
Thanks!

I tried running again with current `master` branch, and now it seems to do something, although it hangs with a frozen screen as nonresponsive:

![image](https://cloud.githubusercontent.com/assets/928045/17633328/b9b67e6a-609a-11e6-96be-a13639c69065.png)

Is this expected?

**Comment by Egan109** [comment]
yes, 
when you click next, the screen should remain for 5-10 minutes depending on the gtfs file this could be longer or less, i will add a loading bar to show progress. the gui shouldn't be malformed like that but shouldn't affect the functionality, 
whens its ready a second window should pop up with addresses.

**Comment by barbeau** [comment]
You're right, it's just a long running operation on the UI thread.  As you say, this should be moved to a background thread and a progress bar displayed.  Here's what I see after letting it run for a while:

![image](https://cloud.githubusercontent.com/assets/928045/17635601/4f4e5ed8-60a6-11e6-92ae-d9748e321861.png)

...and using the links works! :)  Congrats!  :+1: 

So I'll close out this issue, and open a new one for the frozen UI.
