### ISSUE TITLE
Screen freezes when processing GTFS data

### ISSUE THREAD

**Issue by barbeau** [Egan109/core#4]
**Summary:** 

If I try to run the QuickStart with PSTA's GTFS and GTFS-realtime VehiclePositions feed, the UI freezes while the GTFS data is being loaded.

![image](https://cloud.githubusercontent.com/assets/928045/17633328/b9b67e6a-609a-11e6-96be-a13639c69065.png)

GTFS data - [GTFSExport.zip](https://github.com/Egan109/core/files/414092/GTFSExport.zip)

GTFS-realtime vehiclePositions feed - http://ridepsta.net/gtfsrt/vehicles

It would be nice to have a progress bar to indicate to the user that something is happening, especially for 5 min+ operations.

**Steps to reproduce:** 
1. Run QuickStart JAR (`transitimeQuickStart.jar`)
2. Add links to the above GTFS/GTFS-realtime data
3. Set local directory (I used `F:\temp\transitime`)
4. Highlight "Start webapp" and click on "Next"

![image](https://cloud.githubusercontent.com/assets/928045/17602827/582ea71c-5fdc-11e6-891e-cd6a85459c5a.png)

**Expected behavior:** 

See a loading progress bar while GTFS is being loaded

**Observed behavior:** 

Frozen screen

cc @scrudden

**Comment by Egan109** [comment]
I've added a progress bar which provides some data as to what the transitimeQuickStart is doing.
along with the gui no longer freezing which allows users to stop the process during setup.

eadfa42deaf4bb45872c60cb7a4108cb721a9da3 --added progress bar to quickstart

**Comment by Egan109** [comment]
I'm closing issue as it has been fixed

**Comment by barbeau** [comment]
Thanks @Egan109!
