### ISSUE TITLE
Add a license for QuickStart code

### ISSUE THREAD

**Issue by barbeau** [Egan109/core#8]
@Egan109 Could you please add a license header to the new files you created under the GSoC project?

Here's a summary:
1. For new files you created - add the same GPL v3 license header included with other transiTime files:

```
/*
 * This file is part of Transitime.org
 * 
 * Transitime.org is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License (GPL) as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 *
 * Transitime.org is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Transitime.org .  If not, see <http://www.gnu.org/licenses/>.
 */
```
1. For existing files that you edited - you don't need to do anything, as the existing header should indicate GPL v3, and your work is then automatically under GPL v3.

**Comment by Egan109** [comment]
Added license headers to all code

336ae7a8c5ba9942d8023817d7f7d64ffef019da-added licenses

**Comment by barbeau** [comment]
Thanks!  I think the above commit-id is wrong though?  Looks like README changes.

**Comment by Egan109** [comment]
oops, yes your right 

3e28dd3f36ead09831ef0adfba9e107d37488b0b -here is the correct one

**Comment by barbeau** [comment]
Thanks, looks good!  Closing.
